build:
	clang --target=wasm32 -nostdlib -Wl,--no-entry -Wl,--export=actions_to_int -Wl,--export=get_byte_at -Wl,--export=set_byte_at -Wl,--export=get_num_players_ptr -Wl,--export=get_players_ptr -o simple_bot.wasm bot_mem.c bot_actions.c main.c 

copy: build
	cp simple_bot.wasm ../../bots/simple_bot.wasm
