build:
	cargo -Zbuild-std=std,core,panic_abort,proc_macro build --target-dir=target_web/

copy: build
	cp target_web/wasm32-unknown-unknown/debug/scared.wasm ../../bots/scared.wasm

build_release: 
	cargo -Zbuild-std=std,core,panic_abort,proc_macro build --release --target-dir=target_web/

copy_release: build_release
	cp target_web/wasm32-unknown-unknown/release/scared.wasm ../../bots/scared.wasm
