build_math:
	rustc -Copt-level=0 --crate-type=staticlib math.rs --target=wasm32-unknown-unknown -o libmath.a

build_math_release:
	rustc -Copt-level=3 --crate-type=staticlib math.rs --target=wasm32-unknown-unknown -o libmath.a

build_libbot_mem:
	just -u bot_mem/ build

build_libbot_mem_release:
	just -u bot_mem/ build_release

copy_libbot_mem: build_libbot_mem
	cp bot_mem/target_web/wasm32-unknown-unknown/debug/libbot_mem.a . 


copy_libbot_mem_release: build_libbot_mem_release
	cp bot_mem/target_web/wasm32-unknown-unknown/release/libbot_mem.a . 

build: copy_libbot_mem build_math
	clang -O0 -pipe -Wall -Wextra -nostdlib --target=wasm32-unknown-unknown -Wl,--no-entry -Wl,--export=my_realloc,--export=get_num_players_ptr,--export=get_players_ptr,--export=get_num_projectiles_ptr,--export=get_projectiles_ptr,--export=get_projectiles_ptr_ptr,--export=actions_to_int -o aggro.wasm libbot_mem.a libmath.a main.c bot_actions.c 

copy: build
	cp aggro.wasm ../../bots/aggro.wasm

build_release: copy_libbot_mem_release build_math_release
	clang -O3 -flto -pipe -Wall -Wextra -nostdlib --target=wasm32-unknown-unknown -Wl,--no-entry -Wl,--strip-all -Wl,--export=my_realloc,--export=get_num_players_ptr,--export=get_players_ptr,--export=get_num_projectiles_ptr,--export=get_projectiles_ptr,--export=get_projectiles_ptr_ptr,--export=actions_to_int -o aggro.wasm libbot_mem.a libmath.a main.c bot_actions.c 

copy_release: build_release
	cp aggro.wasm ../../bots/aggro.wasm

