[config]
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
# skip_core_tasks = true
# Skips loading Git related environment variables
skip_git_env_info = true
# Skips loading rust related environment variables
# skip_rust_env_info = true
# Skips loading the current crate related environment variables
skip_crate_env_info = true

[tasks.install-target-wasm32-unknown-unknown]
args = ["target", "install", "wasm32-unknown-unknown"]
command = "rustup"

[tasks.basic-http-server]
env = { RUSTFLAGS = "-Ctarget-cpu=native" }
install_crate = {crate_name = "basic-http-server", binary = "basic-http-server", test_arg="--help"}

[tasks.build-web-debug]
env = { RUSTFLAGS = "" }
args = ["build", "--target", "wasm32-unknown-unknown", "--target-dir=target_web/"]
command = "cargo"
dependencies = ["install-target-wasm32-unknown-unknown"]

[tasks.copy-wasm-file-debug]
args = ["target_web/wasm32-unknown-unknown/debug/shooter2.wasm", "target/game.wasm"]
command = "cp"
dependencies = ["build-web-debug"]

[tasks.serve]
args = ["-a", "127.0.0.1:4000"]
command = "basic-http-server"
dependencies = ["basic-http-server", "copy-wasm-file-debug"]

